
server:
  port: 8083

spring:
  application:
    name: sales-service


  #r2dbc:
    #url: r2dbc:postgresql://arkadb.cpeo48mcubi7.us-east-2.rds.amazonaws.com:5432/arka
    #username: Arkchief_DB
    #password: Dragunov2020#$

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/arka
    username: postgres
    password: admin123

    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30s

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    com.arka.ecommerce.msmovement: DEBUG


