version: '3.8'
services:
  sales-db:
    image: postgres:15
    environment:
      POSTGRES_DB: salesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  sales-service:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_R2DBC_URL: r2dbc:postgresql://sales-db:5432/salesdb
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: password
    depends_on:
      - sales-db
    ports:
      - "8083:8083"
