version: '3.8'

services:
  movement-db:
    image: postgres:15
    container_name: movement-db
    environment:
      POSTGRES_DB: movementdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - movement_data:/var/lib/postgresql/data
    networks:
      - arka-net

  msmovement:
    build: .
    container_name: msmovement
    depends_on:
      - movement-db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_R2DBC_URL: r2dbc:postgresql://movement-db:5432/movementdb
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: admin
      SPRING_FLYWAY_URL: jdbc:postgresql://movement-db:5432/movementdb
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: admin
    ports:
      - "8082:8080"
    networks:
      - arka-net

networks:
  arka-net:
    driver: bridge

volumes:
  movement_data:
