server:
  port: 8084

spring:
  application:
    name: msmovement

  main:
    web-application-type: reactive

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/arka
    username: postgres
    password: admin123
    pool:
      enabled: true
      initial-size: 5
      max-size: 20
      max-idle-time: 30s

  jackson:
    serialization:
      indent_output: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.arka.ecommerce.msmovement: DEBUG

# URLs de otros microservicios
services:
  inventory:
    url: http://inventory-service:8080/api/v1/inventory
  sales:
    url: http://sales-service:8083/api/v1/sales
  order:
    url: http://order-service:8080/api/v1/orders

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
